#ifndef __YUM_VERSION_H__
#define __YUM_VERSION_H__

#ifndef YUM_VERSION
#define YUM_VERSION 10000
#endif

#define YUM_VERSION_MAJOR (YUM_VERSION / 10000)
#define YUM_VERSION_MINOR ((YUM_VERSION / 100) % 100)
#define YUM_VERSION_PATCH (YUM_VERSION % 100)

#endif // __YUM_VERSION_H__